name: Tinycloud Frontend Pipeline
on:
    push:
        branches:
            - main
env:
    AWS_REGION: eu-north-1
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
concurrency:
    group: tinycloud-frontend-pipeline
    cancel-in-progress: true
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
          version: ${{ steps.semver.outputs.semver_tag }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Sermver action
              id: semver
              uses: gandarez/semver-action@master
              with:
                bump: patch
                main_branch_name: main

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build and Push Docker image
              run: |
                docker build --no-cache -t tinycloud-frontend:latest .
                docker tag tinycloud-frontend:latest ${{ steps.login-ecr.outputs.registry }}/tinycloud-docker-frontend:${{ steps.semver.outputs.semver_tag }}
                docker push ${{ steps.login-ecr.outputs.registry }}/tinycloud-docker-frontend:${{ steps.semver.outputs.semver_tag }}

            - name: Build and Push Helm chart
              run: |
                helm package charts/tinycloud-frontend --version ${{ steps.semver.outputs.semver_tag }}
                helm push tinycloud-frontend-*.tgz oci://${{ steps.login-ecr.outputs.registry }}

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Setup Kubeconfig
              run: |
                echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
                echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV

            - name: ECR Secret for Kubernetes
              run: |
                kubectl create secret docker-registry ecr-registry-secret \
                  --docker-server=${{ steps.login-ecr.outputs.registry }} \
                  --docker-username=AWS \
                  --docker-password=$(aws ecr get-login-password --region ${{ env.AWS_REGION }}) \
                  -n tinycloud-dev \
                  --dry-run=client -o yaml | kubectl apply -f -

            - name: Deploy to Civo
              run: |
                helm upgrade --install tinycloud-frontend-dev \
                  oci://${{ steps.login-ecr.outputs.registry }}/tinycloud-frontend \
                  --version ${{ needs.build.outputs.version }} \
                  -f charts/tinycloud-frontend/values-dev.yaml \
                  -n tinycloud-dev \
                  --create-namespace
